### ISSUE TITLE
v1.3.0 - "This component was built for a different processor architecture."

### ISSUE THREAD

**Issue by kiriya-aoi** [phw/foo_listenbrainz2#4]
The attempt to
> - Provide a unified package including 32 and 64 bit version of this component.

doesn't appear to have worked on 64-bit fb2k v2.0 beta 3.

`Could not load component "foo_listenbrainz2-v1.3.0.fb2k-component": This component was built for a different processor architecture.`

**Comment by marc2k3** [comment]
I think I know why... 😀 

![image](https://user-images.githubusercontent.com/62050527/188336467-95cdcb1d-2211-4460-99f6-ebaca2992abb.png)

**Comment by phw** [comment]
Thanks both of you. Some stupid packaging issue on the CI not including all files recursively. Fixed now with https://github.com/phw/foo_listenbrainz2/commit/3e0c56969b5919c2dff06db96ea750f136fbff5d, see https://github.com/phw/foo_listenbrainz2/releases/tag/v1.3.1

And @marc2k3 great to see you here :) Any chance you might get interested in this code again? I'm happy to keep this alive, and the code is clean and easy to understand and this component provides the most important features. But C++, the Windows API and foobar2000 SDK are all not really my area of expertise. So any help is appreciated. Also just anytime write me should you have some ideas or complaints on whatever is happening here.

**Comment by marc2k3** [comment]
I only peeked in because I have this page bookmarked.

https://github.com/topics/foobar2000?l=c%2B%2B&o=desc&s=updated

It's all github repos marked with the `foobar2000` topic filtered by C++ and sorted by most recent update.

And no, I have no interest in this. I don't have a metabrainz account and won't be creating one anytime soon. If the musicbrainz API requires one in future, I might come crawling back for that.

**Comment by phw** [comment]
Fair enough. Then I just want let you know that I appreciate you looking by, and thanks a lot for all the effort you put into this component in the past :)
